version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Containerfile
      target: dev
    container_name: muistin
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
    stdin_open: true
    tty: true
    command: bash -c "mix deps.get 2>/dev/null || true && mix deps.compile 2>/dev/null || true && mix phx.server"
